# Generated by Django 4.2.6 on 2023-10-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="club",
            name="opening_time",
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="OpeningTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Montag"),
                            (1, "Dienstag"),
                            (2, "Mittwoch"),
                            (3, "Donnerstag"),
                            (4, "Freitag"),
                            (5, "Samstag"),
                            (6, "Sonntag"),
                        ],
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_times",
                        to="schedule.club",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("club", "weekday", "date")},
            },
        ),
    ]
