# Generated by Django 4.2.6 on 2023-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_remove_club_closing_time_remove_club_opening_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="weekly_hours",
            field=models.FloatField(
                help_text="Bitte geben Sie die wöchentliche Arbeitszeit in Stunden ein.",
                null=True,
            ),
        ),
    ]
