# Generated by Django 4.2.6 on 2023-10-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_employee_weekly_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="weekly_hours",
            field=models.FloatField(
                help_text="Bitte geben Sie die wöchentliche Arbeitszeit in Stunden ein."
            ),
        ),
    ]
