# Generated by Django 4.2.6 on 2023-10-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_employee_weekly_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="color",
            field=models.CharField(
                help_text="Hinterlegen Sie den Farbcode in #hex",
                max_length=7,
                null=True,
            ),
        ),
    ]
