# Generated by Django 4.2.6 on 2023-10-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_alter_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftpreference",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shiftpreference",
            name="day_of_week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shiftpreference",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shiftpreference",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
