# Generated by Django 4.2.6 on 2023-10-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_shiftpreference_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftpreference",
            name="date",
        ),
        migrations.CreateModel(
            name="NonWorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonworking_days",
                        to="schedule.employee",
                    ),
                ),
            ],
        ),
    ]
