# Generated by Django 4.2.6 on 2023-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_remove_shiftpreference_date_nonworkingday"),
    ]

    operations = [
        migrations.AddField(
            model_name="dienstplan",
            name="maximale_arbeitszeit",
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dienstplan",
            name="minimale_arbeitszeit",
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
            preserve_default=False,
        ),
    ]
