# Generated by Django 4.2.6 on 2023-10-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_dienstplan_maximale_arbeitszeit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftpreference",
            name="id",
            field=models.SmallIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
