# Generated by Django 4.2.6 on 2023-10-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_alter_shiftpreference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.SmallIntegerField(
                default=0, primary_key=True, serialize=False
            ),
        ),
    ]
