# Generated by Django 4.2.6 on 2023-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dienstplan",
            name="maximale_arbeitszeit",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="dienstplan",
            name="minimale_arbeitszeit",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
